language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install

# step pending until Apigee credentials are encrypted in Travis by following these steps: http://docs.travis-ci.com/user/encryption-keys/
before_script: grunt default -env=test -username=$ae_username -password=$ae_password -debug